stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
   - docker build -t back-image .

test-job:
  stage: test
  script:
   - docker run --rm back-image pytest -v -s

deploy-job:
  stage: deploy
  script:
   - docker compose up -d