version: '3.8'

services:
  back:
    image: inksne/back-image:latest
    container_name: back-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    env_file:
      - .env
    command: ["python", "main.py"]