name: CI Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/back-image .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker push your-dockerhub-username/back-image:latest

  test:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Pull Docker image from DockerHub
        run: |
          docker pull your-dockerhub-username/back-image:latest

      - name: Run tests
        run: |
          docker run --rm your-dockerhub-username/back-image pytest -v -s

  deploy:
    runs-on: ubuntu-latest
    needs: test  

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose up -d
