name: CI Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  

      - name: Build Docker image
        run: |
          docker build -t back-image .

  test:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          docker run --rm back-image pytest -v -s

  deploy:
    runs-on: ubuntu-latest
    needs: test  

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose up -d